#### NUMPY ===> Numpy is a open- source library that is used for scientific calculations.

#### Why we use numpy whenever we have list?
1] Homogeneous data type

2] ,memory less consume

3] less time consume

#### !pip install numpy

In [7]:
import numpy as np

In [9]:
a = [1,34,67,90]
type(a)

list

In [13]:
b = np.array(a)
b

array([ 1, 34, 67, 90])

In [15]:
type(b)

numpy.ndarray

### Dimension ==>

1] 1-D ===> element exist in x-direction

2] 2-D ===> element exist in x and y direction

3] 3-D ===> element exist in x,y,z direction



In [20]:
print("Total Shape:", b.shape)  ## shape = n(rows), n(columns)

Total Shape: (4,)


In [26]:
print("Total elements:", b.size) ## size = n(row)*n(column)

Total elements: 4


In [28]:
print("Total elements:", b.ndim) ## ndim is refer to dimension of array

Total elements: 1


In [30]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [32]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
type(b)

numpy.ndarray

In [36]:
print("Toatl rows and columns:", b.shape) ## shape = n(row), n(column)
print("Total element:", b.size) ## size = n(row) * n(column)
print("Total dimension:", b.ndim) ## ndim ==> dimension

Toatl rows and columns: (3, 3)
Total element: 9
Total dimension: 2


# How can we create a user defined Array ? 

In [39]:
a = []
size = int(input("Enter size: "))
for i in range(size):
    val = int(input("Enter number: "))
    a.append(val)
b = np.array(a)
b

Enter size:  4
Enter number:  12
Enter number:  45
Enter number:  56
Enter number:  87


array([12, 45, 56, 87])

# Numpy Function


Images ===> Pixels(0-255)px ===> 0px(black), 255px(white) ===> Normalize ===> (0-1)px

- black & white ht, image ===> height, width
- colorfull image ===> height, width, color_channel(red, green, blue)

Matrix ===> n(rows) = n(columns) ===> symmatric matrix, n(r)! = n(c) ===> asymmatric matrix

Random Number generation ===> random module

Data science ===> simple line equation = y = mx + b  (x,y) = co-ordinates, m= weight, b = intercept 

Matrix ===> row, column

Matrix ===> diagonal positional element = [(1,1),(2,2),(3,3),......(n,n)]

# 1) zeros() ===> It will create an array in which all the values are 0

In [46]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [50]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

# 2) ones() ===> It will create an array in which all the values are 1

In [54]:
a = np.ones(3)
a

array([1., 1., 1.])

In [58]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
a.shape

(3, 4)

# 3) eye() ===> It will create an array in which diagonal positional elements are 1 and rest all are 0.

In [72]:
a = np.eye(3)  ## Symmatric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
a = np.eye(3,4) ## Asymmatric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 4) diag() ===> It will create an array in which we can customize our diagonal positional elements 

In [79]:
a = np.diag([1,56,89,700])
a

array([[  1,   0,   0,   0],
       [  0,  56,   0,   0],
       [  0,   0,  89,   0],
       [  0,   0,   0, 700]])

# 5) Random Module ===> 

a] OTP generation

b] Dataset ===> 1 dummy coulumn add

c] randomly weights initialize



### a) Randint (min_number , max_number, total_numbers)


In [86]:
a = np.random.randint(1,10,3)
a

array([1, 4, 1])

### b) Rand(total_numbers) ===> it will return numbers from 0 to 1

In [94]:
a = np.random.rand(5)
a

array([0.8415915 , 0.11784927, 0.95270944, 0.45161758, 0.18939996])

### c) Randn() ===> -3 to +3


In [97]:
a = np.random.randn(5)
a

array([ 0.88166464,  1.34455891, -0.08909688,  0.97565665, -2.45371732])

### d) seed() ===> It will fix our data once the data has been generated.

In [101]:
np.random.seed(20)
a = np.random.randint(1,10,3)
a

array([4, 5, 7])